dark_urshifu_url: "https://nouthuca.com/search/?pokemon[0]=%E3%82%A6%E3%83%BC%E3%83%A9%E3%82%AA%E3%82%B9%E6%82%AA&&rule[%E3%82%B7%E3%83%B3%E3%82%B0%E3%83%AB]=on"
water_urshifu_url: "https://nouthuca.com/search/?pokemon[0]=%E3%82%A6%E3%83%BC%E3%83%A9%E3%82%AA%E3%82%B9%E6%B0%B4&&rule[%E3%82%B7%E3%83%B3%E3%82%B0%E3%83%AB]=on"
param_freq_threshold: 5

use_feature_used_pokemon: True
use_feature_type_frequency: True
use_feature_opponent_advantage: True

# gbdt parameters
learning_rate_gbdt: 0.01
max_depth_gbdt: 8