dark_urshifu_url: "https://nouthuca.com/search/?pokemon%5B0%5D=%E3%82%A6%E3%83%BC%E3%83%A9%E3%82%AA%E3%82%B9%E6%82%AA"
water_urshifu_url: "https://nouthuca.com/search/?pokemon%5B0%5D=%E3%82%A6%E3%83%BC%E3%83%A9%E3%82%AA%E3%82%B9%E6%B0%B4"